version: "3.1"
services:
  db:
    image: mysql:latest
    restart: always

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: core

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
      interval: 3s
      retries: 120

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:3306 -t 30s -i 250ms

  app:
    build: ./app           # Where the Dockerfile is stored
    restart: always

    depends_on:
      wait-for-db:
        condition: service_completed_successfully

    volumes:
      - ./app:/app

    links:
      - db

    ports:
      - "5000:5000"

  